### ISSUE TITLE
Imgproxy is not able to request images over https

### ISSUE THREAD

**Issue by kostrahb** [DarthSim/imgproxy#102]
We have tried to run image proxy in kubernetes and accidentally happened to come across this issue when we tried to get an image over https.

Certificates are installed, probably as dependency of `go`, but when trying to `wget` https page from within pod, the error is that `ssl_client` is missing:
```
wget https://www.google.com
Connecting to www.google.com (216.58.213.228:443)
wget: can't execute 'ssl_client': No such file or directory
wget: error getting response: Connection reset by peer
```

**Comment by DarthSim** [comment]
Sorry, can't reproduce the issue. Imgproxy downloads images over HTTPS just fine:

Original:
https://www.gettyimages.ca/gi-resources/images/Homepage/Hero/UK/CMS_Creative_164657191_Kingfisher.jpg

Imgproxified:
https://imgproxy-test-darthsim.herokuapp.com/unsafe/resize:fit:400:400/sharpen:0/aHR0cHM6Ly93d3cuZ2V0dHlpbWFnZXMuY2EvZ2ktcmVzb3VyY2VzL2ltYWdlcy9Ib21lcGFnZS9IZXJvL1VLL0NNU19DcmVhdGl2ZV8xNjQ2NTcxOTFfS2luZ2Zpc2hlci5qcGc

Wget doesn't work with https inside imgproxy pod because of lack of ssl_client, but go doesn't use one.

**Comment by kostrahb** [comment]
In the end the problem was on our side. But thank you for pointing me in the right direction by showing me working url. I used the command `echo "<url>" | base64` for generating the base64 encoded part of url and `echo` appends newline character to the end of the string so this caused the error. When generating that string with `echo -n "<url>" | base64`, everythings works fine.
