### ISSUE TITLE
Use AWS S3 bucket as image source

### ISSUE THREAD

**Issue by mrcasablr** [DarthSim/imgproxy#11]
S3 is a great place to store images and can be used as an image source. Once images are processed, it can be written to another path.

**Comment by DarthSim** [comment]
Hi!
You can use a link to your image on S3 as a source. We do so on eBay Social.
Saving the results to somewhere will probably never be added to imgproxy. I don't want to add a simple caching which won't do its work properly. At the same time, the good caching system requires some third-party dependencies like key storage. I don't want to break my simplicity principle since CDN and caching servers do this work good.
