### ISSUE TITLE
Allow insecure presets

### ISSUE THREAD

**Issue by printercu** [DarthSim/imgproxy#117]
Hi!

We want to permit users to crop images into limited dimensions list without signing url. So they can generate urls on the client side. I think this can be done with presets: define this presets like `100=resize:fit:100:100:0; 500=...` and start server with `IMGPROXY_INSECURE_PRESETS=100,500`.

WDYT about having this feature in the main repo? I can prepare PR.

**Comment by DarthSim** [comment]
Hi!

I don't see how this can be applied since URL can include other processing options. Also, it is a big security breach. An attacker can spam imgproxy with resizing random images with insecure presets. At my point of view, signing the URL is the only well-tested way to fully protect your application.

**Comment by printercu** [comment]
This is why I think unsigned conversions should be available only for whitelisted presets. If url contains any other options it must be signed. I understand security risks, however using `IMGPROXY_BASE_URL ` to allow conversions of images stored on trusted domains and limited list of available presets should prevent from malicious usage.

**Comment by DarthSim** [comment]
I'm not sure how to implement it properly on the current code base, but I'd like to take a look if you'd made a PR.

**Comment by constb** [comment]
@printercu can't you just put imgproxy behind nginx? filter source urls with regexes in nginx locations and forward the filtered settings to proxy_pass url. I think this should allow you to fine-tune limitations and a list of available options much better than anything imgproxy provides or will provide…

**Comment by printercu** [comment]
Thanks for the idea! We'll give it a try. This feature has been pushed down in our schedule and I don't know when we'll proceed with it. @DarthSim should I close the PR until get updates?

**Comment by DarthSim** [comment]
It's your feature request, so feel free to close it whenever you want :)

Though I agree with @constb. URL limitation is a huge thing. Everyone has their own rules for it and implementing 'em all will complex imgproxy a lot. Since I strongly follow SRP, I'd prefer to keep this kind of functionality out of imgproxy.

**Comment by quotient** [comment]
Hey did anyone end up writing some nginx configs to handle this sort of filtering? @printercu @constb  maybe you?

**Comment by quotient** [comment]
Okay I got a working snippet for white listing sources for the proxy path using nginx. 

Here's the regex :

```
location ~* ^/.+/http.?://(?![^\/]*(source0\.com|source1\.com|whatever\.io)/).*$ {
  return 403;
}

```
Should be the first "location" in config.
Here, source0.com, source1.com, whatever.io are the trusted domains, which won't be blocked.

tested with https://nginx.viraptor.info/
