### ISSUE TITLE
Problem on install

### ISSUE THREAD

**Issue by sonyarianto** [DarthSim/imgproxy#26]
I am using CentOS 7 and already installed vips but when I type
```
go get -f -u github.com/DarthSim/imgproxy
```
this error appear.

```
# pkg-config --cflags vips
Package vips was not found in the pkg-config search path.
Perhaps you should add the directory containing `vips.pc'
to the PKG_CONFIG_PATH environment variable
No package 'vips' found
pkg-config: exit status 1
```

Anyone can help?

UPDATE:
NO PROBLEM, solved, I just add
PKG_CONFIG_PATH point to /usr/local/lib/pkgconfig

**Comment by DarthSim** [comment]
Awesome. Thanks for trying out imgproxy!

**Comment by marckohlbrugge** [comment]
I'm running into this same problem. Unfortunately setting `PKG_CONFIG_PATH` to `/usr/local/lib/pkgconfig` doesn't do anything for me.

**Comment by DarthSim** [comment]
Hey Marc!

Try `pkg-config --libs vips`. If it doesn't see your vips installation, then you should fix this first.
But since you use Docker anyway, why don't use the official imgproxy image? imgproxy relies on lots of dependencies, and I spend a lot of time keeping them updated, patched, etc in the official image.

**Comment by marckohlbrugge** [comment]
@DarthSim Thanks for the quick response! I initially couldn't get the Docker image to work on [Render](https://render.com). I ultimately [figured it out](https://community.render.com/t/how-to-install-imgproxy-using-docker/2097/5) though, so I'm indeed using the official Docker image now. Thanks for the help!
