### ISSUE TITLE
Progressive jpeg support

### ISSUE THREAD

**Issue by volyx** [DarthSim/imgproxy#3]
https://habrahabr.ru/post/165645/

**Comment by shaleh** [comment]
https://calendar.perfplanet.com/2012/progressive-jpegs-a-new-best-practice/ for those us who do not read Cyrillic languages

**Comment by maor** [comment]
+1

**Comment by krutovvv** [comment]
+1

**Comment by DarthSim** [comment]
We could celebrate the anniversary of this feature request, but I forgot :)
I personally not a fan of progressive JPEG in real-time processing because it requires much more time to save the resulting image. Anyway, the feature was added in the latest release. https://github.com/DarthSim/imgproxy#compression

**Comment by volyx** [comment]
Thank you!
