### ISSUE TITLE
https issue

### ISSUE THREAD

**Issue by Robx64** [DarthSim/imgproxy#37]
Because I still have some issues with Https ... Is there any other option than docker ?
For example use it on normal CentOS server ?
if yes how to do it ?
I couldn't find a word about ....

**Comment by DarthSim** [comment]
Hi,

One of the main principles of imgproxy is simplicity. As README says:

> It might be useful to have everything built in — such as HTTPS support — but an easy way to solve that would be just to use a proxying HTTP server such as nginx.

imgproxy itself doesn't support HTTPS connections. If you use some kind of proxy in front of imgproxy (I strongly recommend, actually), you should configure it to use SSL. CDS like CloudFront support HTTPS "out of the box". Or you can make nginx with configured SSL to use imgproxy as upstream. Something like this: https://gist.github.com/DarthSim/ee75da7da21dc984fe5e99ac86509a9f

I'm going to close this issue because it's not related directly to imgproxy.
