### ISSUE TITLE
Feature Request: Multiple local folders

### ISSUE THREAD

**Issue by egorsmkv** [DarthSim/imgproxy#65]
The feature request #42 is good, but can sets one folder only.
It will be more convenient if we would add two or more folders where imgproxy could finds images to resize.

**Comment by DarthSim** [comment]
Hi!
Don't think this is a good idea. First of all, it's technically difficult since `http.NewFileTransport` takes only one filesystem as an argument. Next reason is it will become unpredictable when your folders contain files with the same names.
Putting your folder in the same parent folder will solve your problem.
