### ISSUE TITLE
Serving files from Google Cloud Storage (GCS)

### ISSUE THREAD

**Issue by itsliang** [DarthSim/imgproxy#75]
Currently Amazon S3 is the only cloud storage supported by imgproxy. It would be nice for imgproxy to support Google Cloud Storage as well.

**Comment by DarthSim** [comment]
This feature has been released in `v2.1.0.rc1`. I'd like to kindly ask you to test this feature since I don't have any non-test buckets. Check out the guide to get more info: [Serving files from Google Cloud Storage](https://github.com/DarthSim/imgproxy/blob/version/2.1/docs/serving_files_from_google_cloud_storage.md)

**Comment by itsliang** [comment]
Tried it with signed url. It works like a charm. Good job!!

**Comment by DarthSim** [comment]
Many thanks for testing! Going to release v2.1.0 asap.

**Comment by DarthSim** [comment]
Just released imgproxy v2.1.0 with this and other awesome features. Check out the changelog for details: https://github.com/DarthSim/imgproxy/blob/master/CHANGELOG.md#v210
