### ISSUE TITLE
Support .gif files

### ISSUE THREAD

**Issue by bonafernando** [DarthSim/imgproxy#90]
I have noticed that `.gif` files can be shown as `.jpg` or `.png`.
But `.gif` files can't be shown in it's original format.

It would be nice if imgproxy supports `gif` files, or at least to allow files to be shown on it's original formats, if not supported.

**Comment by DarthSim** [comment]
Hi,

Since libvips doesn't support animated GIFs, I don't see any significant reason to support GIF output. Jpeg works just fine as a lightweight format.
libvips also doesn't have native support of GIF output, and we'd have to use libMagic for it.

I could add support of animated GIFs using some Go package, but this won't probably happen in nearest future.

**Comment by DarthSim** [comment]
Suddenly imgproxy `v2.1.0.rc2` got full GIF support :)
